name: test
on:
  push:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cesiumgs/github-actions/get-pr-id@fordi/get-pr-id
        id: pr_id
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.pr_id.outputs.value == '' }}
        run: "echo No PR"
      - if: ${{ steps.pr_id.outputs.value != '' }}
        run: "echo PR: ${{ steps.pr_id.outputs.value }}"

