name: test
on:
  push:
  pull_request:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/get-pr-id
      - if: ${{ env.pr_id == '' }}
        run: "echo No PR"
      - if: ${{ env.pr_id != '' }}
        run: "echo PR: ${{ env.pr_id }}"

